version: '3'

volumes:
  pgadmin_data: {}

services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "15432:80"
    volumes: 
      - pgadmin_data:/var/lib/pgadmin

networks:
  app-network:
    driver: bridge
